In [292]:
import pandas as pd
import csv

In [293]:
df = pd.read_csv('./data/weather-stations/kelowna/kelowna_stations.csv')

In [294]:
df.sort_values(by=['Latitude'], ascending = True)

,Network ID,Network Name,Native ID,Station ID,Station Name,History ID,Province,Longitude,Latitude,Elevation (m),Record Start,Record End,Obs Freq,Variables
78,1,EC,1131410,1112,CARMI,1515,BC,-119.083333,49.500000,1245.0,1924-01-01,1969-03-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
7,1,EC,1126160,243,PENTICTON SEWAGE PLANT,646,BC,-119.600000,49.500000,344.0,1954-10-01,1969-11-30,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
285,17,ARDA,112254,4998,ROGER RCH DS,6678,BC,-119.777500,49.513333,832.0,1980-10-08,1981-07-22,Daily,Precipitation Amount|Surface Snow Depth (Point)
145,12,FLNRO-WMB,328,1876,PENTICTON RS,2279,BC,-119.553300,49.518300,427.0,1988-08-16,2023-10-08,Hourly,Dew Point Temperature|Precipitation Amount|Pre...
165,12,FLNRO-WMB,393,1936,NICOLL,2339,BC,-118.360300,49.526700,866.0,1988-10-28,2024-01-14,Hourly,Dew Point Temperature|Precipitation Amount|Pre...
486,12,FLNRO-WMB,1180,11000,ZZ RED CREEK TEMP,13168,BC,-120.220833,49.529167,1400.0,2014-06-25,2018-09-11,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
247,17,ARDA,112154,4956,PENTICTON CK,6636,BC,-119.503333,49.530000,1140.0,1971-04-01,1972-11-02,Daily,Precipitation (Cumulative)|Surface Snow Depth ...
303,17,ARDA,113072,5071,LAKEVALE,6751,BC,-119.076667,49.535000,887.0,1971-04-26,1972-09-29,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
189,14,ENV-ASP,2E07P,2553,Grano Creek,2956,BC,-118.683000,49.550000,1860.0,1997-07-24,2020-10-01,Daily,Precipitation 1hr|Precipitation Amount|Precipi...
44,1,EC,1125381,1057,NARAMATA,1460,BC,-119.566667,49.550000,411.0,1971-04-01,2004-02-29,Daily,Precipitation Amount|Precipitation Climatology...
512,12,FLNRO-WMB,1392,12523,MCNULTY EXT,14545,BC,-120.173222,49.555694,1595.0,2020-06-15,2024-01-13,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
290,17,ARDA,113024,5029,LWR TRAPPING,6709,BC,-119.045833,49.562500,899.0,1965-11-04,1975-09-09,Daily,Relative Humidity (Mean)|Temperature (Max.)|Te...
429,19,EC_raw,112G8L1,6658,Summerland,8679,BC,-119.648694,49.562556,454.2,2012-11-19,2012-11-20,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
455,19,EC_raw,112G8L1,6658,Summerland,12101,BC,-119.648694,49.562556,454.2,2012-12-03,2012-12-04,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
463,19,EC_raw,112G8L1,6658,Summerland,12110,BC,-119.648694,49.562556,454.2,2012-12-07,2012-12-08,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
427,19,EC_raw,112G8L1,6658,Summerland,8677,BC,-119.648694,49.562556,454.2,2012-11-18,2012-11-19,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
459,19,EC_raw,112G8L1,6658,Summerland,12105,BC,-119.648694,49.562556,454.2,2012-12-05,2012-12-06,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
425,19,EC_raw,112G8L1,6658,Summerland,8675,BC,-119.648694,49.562556,454.2,2012-11-17,2012-11-18,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
457,19,EC_raw,112G8L1,6658,Summerland,12103,BC,-119.648694,49.562556,454.2,2012-12-04,2012-12-05,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
431,19,EC_raw,112G8L1,6658,Summerland,8681,BC,-119.648694,49.562556,454.2,2012-11-20,2024-01-14,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
451,19,EC_raw,112G8L1,6658,Summerland,12097,BC,-119.648694,49.562556,454.2,2012-12-01,2012-12-02,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
433,19,EC_raw,112G8L1,6658,Summerland,8683,BC,-119.648694,49.562556,454.2,2012-11-21,2012-11-22,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
435,19,EC_raw,112G8L1,6658,Summerland,8685,BC,-119.648694,49.562556,454.2,2012-11-22,2012-11-23,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
461,19,EC_raw,112G8L1,6658,Summerland,12107,BC,-119.648694,49.562556,454.2,2012-12-06,2012-12-07,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
437,19,EC_raw,112G8L1,6658,Summerland,12083,BC,-119.648694,49.562556,454.2,2012-11-23,2012-11-24,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
439,19,EC_raw,112G8L1,6658,Summerland,12085,BC,-119.648694,49.562556,454.2,2012-11-24,2012-11-25,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
449,19,EC_raw,112G8L1,6658,Summerland,12095,BC,-119.648694,49.562556,454.2,2012-11-30,2012-12-01,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
441,19,EC_raw,112G8L1,6658,Summerland,12087,BC,-119.648694,49.562556,454.2,2012-11-25,2012-11-26,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
447,19,EC_raw,112G8L1,6658,Summerland,12093,BC,-119.648694,49.562556,454.2,2012-11-28,2012-11-30,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
453,19,EC_raw,112G8L1,6658,Summerland,12099,BC,-119.648694,49.562556,454.2,2012-12-02,2012-12-03,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
445,19,EC_raw,112G8L1,6658,Summerland,12091,BC,-119.648694,49.562556,454.2,2012-11-27,2012-11-28,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
443,19,EC_raw,112G8L1,6658,Summerland,12089,BC,-119.648694,49.562556,454.2,2012-11-26,2012-11-27,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
465,19,EC_raw,112G8L1,6658,Summerland,12112,BC,-119.648694,49.562556,454.2,2012-12-08,2012-12-09,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
473,19,EC_raw,112G8L1,6658,Summerland,12127,BC,-119.648694,49.562556,454.2,2012-12-12,2012-12-13,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
423,19,EC_raw,112G8L1,6658,Summerland,8673,BC,-119.648694,49.562556,454.2,2012-11-16,2012-11-17,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
415,19,EC_raw,112G8L1,6658,Summerland,8665,BC,-119.648694,49.562556,454.2,2012-11-12,2012-11-13,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
471,19,EC_raw,112G8L1,6658,Summerland,12123,BC,-119.648694,49.562556,454.2,2012-12-11,2012-12-12,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
477,19,EC_raw,112G8L1,6658,Summerland,12136,BC,-119.648694,49.562556,454.2,2012-12-14,2018-08-30,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
417,19,EC_raw,112G8L1,6658,Summerland,8667,BC,-119.648694,49.562556,454.2,2012-11-13,2012-11-14,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
475,19,EC_raw,112G8L1,6658,Summerland,12132,BC,-119.648694,49.562556,454.2,2012-12-13,2012-12-14,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
419,19,EC_raw,112G8L1,6658,Summerland,8669,BC,-119.648694,49.562556,454.2,2012-11-14,2012-11-15,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
413,19,EC_raw,112G8L1,6658,Summerland,8663,BC,-119.648694,49.562556,454.2,2012-11-11,2012-11-12,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
411,19,EC_raw,112G8L1,6658,Summerland,8661,BC,-119.648694,49.562556,454.2,2010-03-02,2019-01-01,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
469,19,EC_raw,112G8L1,6658,Summerland,12119,BC,-119.648694,49.562556,454.2,2012-12-10,2012-12-11,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
421,19,EC_raw,112G8L1,6658,Summerland,8671,BC,-119.648694,49.562556,454.2,2012-11-15,2012-11-16,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
467,19,EC_raw,112G8L1,6658,Summerland,12115,BC,-119.648694,49.562556,454.2,2012-12-09,2012-12-10,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
249,17,ARDA,112164,4959,CONKLE,6639,BC,-119.686667,49.563333,593.0,1971-03-16,1972-10-30,Daily,Precipitation (Cumulative)|Relative Humidity (...
74,1,EC,112G8L1,1105,SUMMERLAND CS,1508,BC,-119.638400,49.563720,454.2,1990-06-01,2017-12-31,Daily,Precipitation Amount|Precipitation Climatology...
438,19,EC_raw,112G8L1,6658,Summerland,12084,BC,-119.638389,49.563722,454.2,2012-11-22,2012-11-22,Daily,Air Pressure Tendency|Dew Point Temperature (P...
410,19,EC_raw,112G8L1,6658,Summerland,8343,BC,-119.638389,49.563722,454.2,2011-05-31,2012-11-08,Hourly,Air Pressure Tendency|Dew Point Temperature (P...
442,19,EC_raw,112G8L1,6658,Summerland,12088,BC,-119.638389,49.563722,454.2,2012-11-24,2012-11-24,Daily,Air Pressure Tendency|Dew Point Temperature (P...
440,19,EC_raw,112G8L1,6658,Summerland,12086,BC,-119.638389,49.563722,454.2,2012-11-23,2012-11-23,Daily,Air Pressure Tendency|Dew Point Temperature (P...
412,19,EC_raw,112G8L1,6658,Summerland,8662,BC,-119.638389,49.563722,454.2,2012-11-09,2012-11-09,Daily,Air Pressure Tendency|Dew Point Temperature (P...
434,19,EC_raw,112G8L1,6658,Summerland,8684,BC,-119.638389,49.563722,454.2,2012-11-20,2012-11-20,Daily,Air Pressure Tendency|Dew Point Temperature (P...
414,19,EC_raw,112G8L1,6658,Summerland,8664,BC,-119.638389,49.563722,454.2,2012-11-10,2012-11-10,Daily,Air Pressure Tendency|Dew Point Temperature (P...
416,19,EC_raw,112G8L1,6658,Summerland,8666,BC,-119.638389,49.563722,454.2,2012-11-11,2012-11-11,Daily,Air Pressure Tendency|Dew Point Temperature (P...
430,19,EC_raw,112G8L1,6658,Summerland,8680,BC,-119.638389,49.563722,454.2,2012-11-18,2012-11-18,Daily,Air Pressure Tendency|Dew Point Temperature (P...
418,19,EC_raw,112G8L1,6658,Summerland,8668,BC,-119.638389,49.563722,454.2,2012-11-12,2012-11-12,Daily,Air Pressure Tendency|Dew Point Temperature (P...
428,19,EC_raw,112G8L1,6658,Summerland,8678,BC,-119.638389,49.563722,454.2,2012-11-17,2012-11-17,Daily,Air Pressure Tendency|Dew Point Temperature (P...
420,19,EC_raw,112G8L1,6658,Summerland,8670,BC,-119.638389,49.563722,454.2,2012-11-13,2020-09-17,Daily,Air Pressure Tendency|Dew Point Temperature (P...
426,19,EC_raw,112G8L1,6658,Summerland,8676,BC,-119.638389,49.563722,454.2,2012-11-16,2023-01-23,Daily,Air Pressure Tendency|Dew Point Temperature (P...
422,19,EC_raw,112G8L1,6658,Summerland,8672,BC,-119.638389,49.563722,454.2,2012-11-14,2012-11-14,Daily,Air Pressure Tendency|Dew Point Temperature (P...
424,19,EC_raw,112G8L1,6658,Summerland,8674,BC,-119.638389,49.563722,454.2,2012-11-15,2012-11-15,Daily,Air Pressure Tendency|Dew Point Temperature (P...
436,19,EC_raw,112G8L1,6658,Summerland,8686,BC,-119.638389,49.563722,454.2,2012-11-21,2012-11-21,Daily,Air Pressure Tendency|Dew Point Temperature (P...
432,19,EC_raw,112G8L1,6658,Summerland,8682,BC,-119.638389,49.563722,454.2,2012-11-19,2012-11-19,Daily,Air Pressure Tendency|Dew Point Temperature (P...
446,19,EC_raw,112G8L1,6658,Summerland,12092,BC,-119.638389,49.563722,454.2,2012-11-26,2012-11-26,Daily,Air Pressure Tendency|Dew Point Temperature (P...
456,19,EC_raw,112G8L1,6658,Summerland,12102,BC,-119.638389,49.563722,454.2,2012-12-02,2012-12-02,Daily,Air Pressure Tendency|Dew Point Temperature (P...
464,19,EC_raw,112G8L1,6658,Summerland,12111,BC,-119.638389,49.563722,454.2,2012-12-06,2012-12-06,Daily,Air Pressure Tendency|Dew Point Temperature (P...
462,19,EC_raw,112G8L1,6658,Summerland,12108,BC,-119.638389,49.563722,454.2,2012-12-05,2012-12-05,Daily,Air Pressure Tendency|Dew Point Temperature (P...
444,19,EC_raw,112G8L1,6658,Summerland,12090,BC,-119.638389,49.563722,454.2,2012-11-25,2012-11-25,Daily,Air Pressure Tendency|Dew Point Temperature (P...
460,19,EC_raw,112G8L1,6658,Summerland,12106,BC,-119.638389,49.563722,454.2,2012-12-04,2012-12-04,Daily,Air Pressure Tendency|Dew Point Temperature (P...
458,19,EC_raw,112G8L1,6658,Summerland,12104,BC,-119.638389,49.563722,454.2,2012-12-03,2012-12-03,Daily,Air Pressure Tendency|Dew Point Temperature (P...
470,19,EC_raw,112G8L1,6658,Summerland,12121,BC,-119.638389,49.563722,454.2,2012-12-09,2012-12-09,Daily,Air Pressure Tendency|Dew Point Temperature (P...
454,19,EC_raw,112G8L1,6658,Summerland,12100,BC,-119.638389,49.563722,454.2,2012-12-01,2012-12-01,Daily,Air Pressure Tendency|Dew Point Temperature (P...
472,19,EC_raw,112G8L1,6658,Summerland,12125,BC,-119.638389,49.563722,454.2,2012-12-10,2012-12-10,Daily,Air Pressure Tendency|Dew Point Temperature (P...
466,19,EC_raw,112G8L1,6658,Summerland,12113,BC,-119.638389,49.563722,454.2,2012-12-07,2012-12-07,Daily,Air Pressure Tendency|Dew Point Temperature (P...
474,19,EC_raw,112G8L1,6658,Summerland,12129,BC,-119.638389,49.563722,454.2,2012-12-11,2012-12-11,Daily,Air Pressure Tendency|Dew Point Temperature (P...
452,19,EC_raw,112G8L1,6658,Summerland,12098,BC,-119.638389,49.563722,454.2,2012-11-30,2012-11-30,Daily,Air Pressure Tendency|Dew Point Temperature (P...
468,19,EC_raw,112G8L1,6658,Summerland,12117,BC,-119.638389,49.563722,454.2,2012-12-08,2012-12-08,Daily,Air Pressure Tendency|Dew Point Temperature (P...
448,19,EC_raw,112G8L1,6658,Summerland,12094,BC,-119.638389,49.563722,454.2,2012-11-28,2012-11-28,Daily,Air Pressure Tendency|Dew Point Temperature (P...
476,19,EC_raw,112G8L1,6658,Summerland,12134,BC,-119.638389,49.563722,454.2,2012-12-12,2012-12-12,Daily,Air Pressure Tendency|Dew Point Temperature (P...
450,19,EC_raw,112G8L1,6658,Summerland,12096,BC,-119.638389,49.563722,454.2,2012-11-29,2012-11-29,Daily,Air Pressure Tendency|Dew Point Temperature (P...
58,1,EC,1127830,1088,SUMMERLAND CDA EL,1491,BC,-119.633333,49.566667,346.0,1949-06-01,1964-09-30,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
57,1,EC,1127800,1087,SUMMERLAND CDA,1490,BC,-119.650000,49.566667,455.0,1916-01-01,2001-01-01,Daily,Precipitation Amount|Precipitation Climatology...
235,17,ARDA,112055,4871,DINGWALL,6551,BC,-119.666667,49.568056,494.0,1974-03-22,1974-10-28,Daily,Temperature (Max.)|Temperature (Min.)
151,12,FLNRO-WMB,338,1885,ZZ AGUR LAKE (NEC),2288,BC,-119.825000,49.570000,1189.0,1989-10-02,2000-11-01,Hourly,Precipitation Amount|Precipitation Climatology...
248,17,ARDA,112163,4958,GARTRELL,6638,BC,-119.634167,49.575000,357.0,1971-03-23,1972-10-29,Daily,Precipitation (Cumulative)|Relative Humidity (...
24,1,EC,1120M47,1017,ARAWANA,1420,BC,-119.566667,49.583333,518.0,1970-12-01,2001-01-01,Daily,Precipitation Amount|Precipitation Climatology...
250,17,ARDA,112165,4960,FAULDER,6640,BC,-119.713333,49.593889,556.0,1971-03-16,1972-05-23,Daily,Precipitation (Cumulative)|Relative Humidity (...
484,12,FLNRO-WMB,1151,10996,ZZ BULL CREEK TEMP,13162,BC,-119.974717,49.594717,1407.0,2013-05-30,2014-10-01,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
233,17,ARDA,112052,4868,DESCHAMPS,6548,BC,-119.755833,49.595000,686.0,1971-04-28,1972-09-28,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
56,1,EC,1127798,1086,SUMMERLAND,1489,BC,-119.666667,49.600000,335.0,1907-07-01,1923-06-30,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
291,17,ARDA,113059,5058,CHRISTIAN V ASB,6738,BC,-118.790000,49.600000,857.0,1969-06-11,1972-10-30,Daily,Precipitation (Cumulative)|Surface Snow Depth ...
245,17,ARDA,112126,4936,CHENG,6616,BC,-119.420833,49.604167,1804.0,1983-09-28,1991-02-28,Daily,Precipitation (Cumulative)|Precipitation Amoun...
223,17,ARDA,112032,4848,STRAFEHL,6528,BC,-119.680556,49.609722,488.0,1974-03-21,1975-09-18,Daily,Temperature (Max.)|Temperature (Min.)
251,17,ARDA,112167,4961,JONES FLAT,6641,BC,-119.670000,49.610833,485.0,1971-03-23,1972-10-29,Daily,Precipitation (Cumulative)|Relative Humidity (...
510,14,ENV-ASP,2F08P,12499,Greyback Resevoir,14521,BC,-119.422400,49.615800,1550.0,2019-12-10,2021-12-08,Unspecified,Cumulative Precipitation|Precipitation 1hr|Pre...
43,1,EC,1125380,1056,NARAMATA,1459,BC,-119.600000,49.616667,366.0,1924-01-01,1936-12-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
232,17,ARDA,112051,4867,DENIKE,6547,BC,-119.846667,49.620833,957.0,1971-03-31,1972-10-30,Daily,Precipitation (Cumulative)|Surface Snow Depth ...
244,17,ARDA,112125,4935,DENNIS CK,6615,BC,-119.412500,49.623611,1792.0,1983-09-28,1991-02-26,Daily,Precipitation (Cumulative)|Precipitation Amoun...
488,12,FLNRO-WMB,1212,11412,ZZ KIRTON TS,13473,BC,-120.023333,49.637783,1491.0,2015-06-02,2015-10-06,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
243,17,ARDA,112124,4934,PENTICTON 2,6614,BC,-119.369444,49.638889,1570.0,1983-09-28,1991-02-26,Daily,Precipitation (Cumulative)|Precipitation Amoun...
231,17,ARDA,112050,4866,RIDDLE,6546,BC,-119.919167,49.645000,850.0,1971-05-27,1972-09-28,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
246,17,ARDA,112153,4955,GREYBACK,6635,BC,-119.370833,49.647500,1659.0,1971-04-14,1972-10-05,Daily,Precipitation (Cumulative)|Surface Snow Depth ...
493,12,FLNRO-WMB,1254,12017,ZZ LOST CHAIN TS,14074,BC,-120.066667,49.648617,1633.0,2015-08-06,2016-10-12,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
79,1,EC,1131615,1113,CHRISTIAN VALLEY,1516,BC,-118.750000,49.650000,805.0,1972-06-19,2001-01-01,Daily,Precipitation Amount|Precipitation Climatology...
234,17,ARDA,112053,4869,ENEAS,6549,BC,-119.792500,49.658333,716.0,1971-03-26,1972-10-30,Daily,Precipitation (Cumulative)|Relative Humidity (...
292,17,ARDA,113060,5059,COPPERKETTLE,6739,BC,-118.779444,49.661944,866.0,1969-06-29,1972-09-29,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
3,1,EC,1124260,235,KIRTON,638,BC,-119.950000,49.666667,884.0,1928-09-01,1962-04-30,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
252,17,ARDA,112169,4962,ACLAND,6642,BC,-119.720833,49.666944,389.0,1971-04-28,1972-09-27,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
304,17,ARDA,113076,5074,STERLING,6754,BC,-119.088333,49.670833,1061.0,1971-04-26,1972-08-30,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
25,1,EC,1121620,1020,CHUTE LAKE,1423,BC,-119.533333,49.683333,1194.0,1928-09-01,1962-10-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
230,17,ARDA,112049,4865,KIRTON,6545,BC,-119.977500,49.689167,945.0,1971-04-27,1972-09-28,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
293,17,ARDA,113061,5060,DAMFINO,6740,BC,-118.772778,49.700000,875.0,1969-06-29,1972-09-29,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
23,1,EC,1120633,1015,BANKIER CHAIN LAKE,1418,BC,-120.283333,49.700000,1020.0,1974-05-01,2001-01-01,Daily,Precipitation Amount|Precipitation Climatology...
48,1,EC,1125880,1072,OSPREY LAKE,1475,BC,-120.183333,49.700000,1099.0,1928-09-01,1952-05-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
149,12,FLNRO-WMB,335,1883,ZZ IDA BELL LAKE,2286,BC,-119.200000,49.700000,12.0,1986-05-22,1988-07-26,Daily,Precipitation Amount|Relative Humidity (Mean)|...
148,12,FLNRO-WMB,332,1880,ZZ CHAIN LAKE,2283,BC,-120.300000,49.700000,10.0,1979-05-01,2000-10-01,Daily,Precipitation Amount|Precipitation Climatology...
146,12,FLNRO-WMB,329,1877,ZZ LITTLE WHITE,2280,BC,-119.300000,49.700000,0.0,1977-05-16,2000-10-01,Daily,Precipitation Amount|Precipitation Climatology...
53,1,EC,1126078,1077,PEACHLAND GREATA RANCH,1480,BC,-119.741200,49.700330,398.0,1994-06-01,2008-06-30,Daily,Precipitation Amount|Precipitation Climatology...
229,17,ARDA,112048,4864,THIRSK,6544,BC,-120.055833,49.711667,1013.0,1971-04-27,1972-09-28,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
289,17,ARDA,113023,5028,UPR TRAPPING,6708,BC,-118.935000,49.712500,1204.0,1965-11-05,1975-09-09,Daily,Precipitation (Cumulative)|Precipitation Amoun...
485,12,FLNRO-WMB,1178,10998,ZZ CENTER MOUNTAIN TEMP,13164,BC,-118.740000,49.713883,1393.0,2014-06-16,2014-10-28,Unspecified,Precipitation Amount|Relative Humidity (Mean)|...
227,17,ARDA,112046,4862,OSPREY LK ASB,6542,BC,-120.233333,49.715833,1098.0,1971-04-04,1972-10-30,Daily,Precipitation (Cumulative)|Surface Snow Depth ...
22,1,EC,1120630,1014,BANKEIR,1417,BC,-120.233333,49.716667,1097.0,1954-08-20,1959-07-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
228,17,ARDA,112047,4863,TSUH,6543,BC,-120.166667,49.720000,1082.0,1971-05-27,1972-08-28,Irregular,Precipitation (Cumulative)|Surface Snow Depth ...
0,1,EC,1120090,231,ADRA,634,BC,-119.583333,49.733333,1003.0,1928-09-01,1953-08-31,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
76,1,EC,1130874,1109,BIG WHITE,1512,BC,-118.933333,49.733333,1841.0,1981-02-01,2001-01-01,Daily,Precipitation Amount|Precipitation Climatology...
77,1,EC,1130875,1110,BIG WHITE MTN LODGE,1513,BC,-118.933333,49.733333,1844.0,1965-03-01,1968-06-30,Daily,Precipitation Amount|Rainfall Amount|Snowfall ...
288,17,ARDA,113022,5027,BIG WHITE,6707,BC,-118.933333,49.733333,1844.0,1965-11-05,1975-09-09,Daily,Precipitation (Cumulative)|Relative Humidity (...

In [295]:
total_burn_data = pd.read_csv("./data/satellite-burn/satellite_burn_cleaned.csv")
total_burn_data[:70]

   IGNITION_DATE  FIRE_SIZE_HA  LATITUDE  LONGITUDE
0     2017/01/01         0.009   49.1217  -115.9226
1     2017/01/01         0.009   51.6025  -122.2677
2     2017/02/10         0.009   50.8894  -119.3201
3     2017/03/01         0.009   52.1870  -121.9566
4     2017/03/13         0.750   49.1705  -116.5328
5     2017/04/01         8.700   50.2925  -121.6444
6     2017/04/01         0.000   49.5282  -123.8333
7     2017/04/03         1.200   51.9963  -123.1572
8     2017/04/03         0.009   51.9366  -122.9875
9     2017/04/03         0.009   50.1729  -119.3620
10    2017/04/04         0.009   51.3226  -117.0155
11    2017/04/04         1.940   52.0903  -123.2556
12    2017/04/05         0.900   53.3286  -120.2126
13    2017/04/05         1.000   50.7968  -121.6136
14    2017/04/05         0.009   51.5273  -122.2801
15    2017/04/06         0.000   56.0726  -120.6078
16    2017/04/06         8.700   51.9492  -123.1352
17    2017/04/09         0.300   51.9314  -122.9369
18    2017/04/09         0.400   52.0113  -123.1633
19    2017/04/09         0.266   51.9384  -123.0151
20    2017/04/09         0.400   53.9183  -124.1717
21    2017/04/10         0.500   51.9985  -123.1556
22    2017/04/10         0.009   51.6329  -122.4137
23    2017/04/10         0.009   49.0927  -119.5650
24    2017/04/11         0.840   52.1001  -123.4028
25    2017/04/11         0.300   50.2691  -121.5977
26    2017/04/14         0.070   50.2699  -121.5989
27    2017/04/15         0.001   49.5875  -116.7814
28    2017/04/16        16.000   55.5009  -127.7669
29    2017/04/16         0.009   50.4112  -121.2997
30    2017/04/17        21.000   55.3875  -127.6784
31    2017/04/17         0.100   55.4225  -127.7088
32    2017/04/17         2.200   55.5366  -127.8604
33    2017/04/17         0.600   55.2862  -128.0777
34    2017/04/17         0.000   55.2795  -128.0700
35    2017/04/17         0.000   49.3026  -124.3120
36    2017/04/18         0.000   51.9742  -123.1504
37    2017/04/18         0.700   51.3393  -120.1552
38    2017/04/19         0.009   51.9401  -123.0959
39    2017/04/20         0.009   49.8146  -120.8651
40    2017/04/20         0.009   55.3560  -122.6108
41    2017/04/20         0.000   52.2023  -119.3681
42    2017/04/20         0.000   52.0392  -119.3118
43    2017/04/20         0.000   52.2175  -119.1550
44    2017/04/20         0.000   52.0350  -119.3000
45    2017/04/21         0.000   53.3712  -122.6368
46    2017/04/21         0.009   49.8166  -119.7586
47    2017/04/21         8.000   51.9897  -123.1615
48    2017/04/22         7.800   55.4164  -127.6185
49    2017/04/22         0.600   50.1488  -120.8770
50    2017/04/23         8.100   55.2346  -128.0477
51    2017/04/23         6.200   55.2496  -127.6674
52    2017/04/24         0.009   52.6167  -122.4574
53    2017/04/24         0.800   54.2843  -124.2657
54    2017/04/24         0.000   54.2214  -130.0585
55    2017/04/25         0.009   55.2571  -128.0519
56    2017/04/25         0.000   54.0010  -122.6268
57    2017/04/25         0.800   54.5775  -124.5605
58    2017/04/26         0.000   51.9625  -122.0245
59    2017/04/26         0.150   56.3386  -121.0775
60    2017/04/26         0.000   49.1967  -124.1332
61    2017/04/27         1.600   54.0178  -126.1924
62    2017/04/27         6.000   55.7177  -121.2105
63    2017/04/27         0.009   54.8848  -126.6898
64    2017/04/28         0.400   51.9487  -123.1342
65    2017/04/28         0.000   58.8064  -122.7322
66    2017/04/28         0.000   58.8295  -122.7561
67    2017/04/28         0.009   53.9441  -123.8795
68    2017/04/29         0.009   53.3012  -122.6894
69    2017/04/29         3.200   56.2145  -121.4275

In [296]:
total_burn_data['LATITUDE'] = pd.to_numeric(total_burn_data['LATITUDE'], errors='coerce')
total_burn_data['LONGITUDE'] = pd.to_numeric(total_burn_data['LONGITUDE'], errors='coerce')

total_burn_data.dropna(subset=['LATITUDE', 'LONGITUDE'], inplace=True)

In [313]:
def spatially_split_stations(df, num_long_splits, num_lat_splits):
    longitude_max = df['Longitude'].max()
    longitude_min = df['Longitude'].min()
    latitude_max = df['Latitude'].max()
    latitude_min = df['Latitude'].min()
    longitude_distance = longitude_max - longitude_min
    latitude_distance = latitude_max - latitude_min
    
    long_split_distance = longitude_distance / num_long_splits
    lat_split_distance = latitude_distance / num_lat_splits
    
    long_track = longitude_min
    lat_track = latitude_min
    print(f"min_long = {longitude_min}, min_lat = {latitude_min}, max_long = {longitude_max}, max_lat = {latitude_max}, long_split = {long_split_distance}, lat_split = {lat_split_distance}")
    zero_count = 0
    num_above = 0
    
    for i in range(num_lat_splits):
        lat_track = latitude_min + i * lat_split_distance
        for j in range(num_long_splits):
            long_track = longitude_min + j * long_split_distance
            
            latitude_mask_station = (df['Latitude'] < lat_track + lat_split_distance) & (df['Latitude'] >= lat_track)
            longitude_mask_station = (df['Longitude'] < long_track + long_split_distance) & (df['Longitude'] >= long_track)
            
            latitude_mask_burn = (burn_data['LATITUDE'] < lat_track + lat_split_distance) & (burn_data['LATITUDE'] >= lat_track)
            longitude_mask_burn = (burn_data['LONGITUDE'] < long_track + long_split_distance) & (burn_data['LONGITUDE'] >= long_track)
            
            station_df = df[latitude_mask_station & longitude_mask_station]
            single_burn = burn_data[latitude_mask_burn & longitude_mask_burn]['FIRE_SIZE_HA'].sum(axis=0)
            burn_array_sample.append(single_burn)
            
            print(f"total burn is {single_burn}")
            
            if single_burn >= 0.01: # in order to see number of regions with noticeable burn area
                num_above += 1
                
            if len(station_df) == 0: 
                zero_count += 1
            station_df.to_csv(f"data/weather-stations/kelowna/fine_area_{i*num_long_splits+j+1}_stations.csv")
            
            print(f"num of stations to aggregate is {len(station_df)}")
            
    print(f"zero count is {zero_count}")
    print(f"num burn above 0.01 is {num_above}")

In [314]:
spatially_split_stations(df, 6, 6)

min_long = -120.330555555556, min_lat = 49.5, max_long = -118.193333333333, max_lat = 51.0, long_split = 0.3562037037038337, lat_split = 0.25
total burn is 0.4
num of stations to aggregate is 15
total burn is 2376.863
num of stations to aggregate is 87
total burn is 16.454
num of stations to aggregate is 14
total burn is 1.263
num of stations to aggregate is 11
total burn is 0.21800000000000003
num of stations to aggregate is 6
total burn is 1096.0
num of stations to aggregate is 1
total burn is 5.215
num of stations to aggregate is 6
total burn is 4108.0289999999995
num of stations to aggregate is 18
total burn is 18.107999999999997
num of stations to aggregate is 55
total burn is 1.854
num of stations to aggregate is 10
total burn is 0.036
num of stations to aggregate is 8
total burn is 0.0
num of stations to aggregate is 5
total burn is 9.814
num of stations to aggregate is 8
total burn is 1.9289999999999998
num of stations to aggregate is 5
total burn is 0.166
num of stations to aggregate is 19
total burn is 14.672
num of stations to aggregate is 14
total burn is 1717.809
num of stations to aggregate is 5
total burn is 0.018
num of stations to aggregate is 10
total burn is 2.0180000000000002
num of stations to aggregate is 5
total burn is 323.254
num of stations to aggregate is 7
total burn is 1.3269999999999997
num of stations to aggregate is 17
total burn is 4.763
num of stations to aggregate is 15
total burn is 606.59
num of stations to aggregate is 8
total burn is 788.6270000000001
num of stations to aggregate is 4
total burn is 1093.381
num of stations to aggregate is 17
total burn is 0.045
num of stations to aggregate is 18
total burn is 0.272
num of stations to aggregate is 21
total burn is 4.827000000000001
num of stations to aggregate is 19
total burn is 3956.381
num of stations to aggregate is 11
total burn is 192.22699999999998
num of stations to aggregate is 3
total burn is 0.8900000000000001
num of stations to aggregate is 14
total burn is 299.59899999999993
num of stations to aggregate is 15
total burn is 0.07199999999999998
num of stations to aggregate is 19
total burn is 0.835
num of stations to aggregate is 13
total burn is 12.597999999999999
num of stations to aggregate is 4
total burn is 230.86399999999992
num of stations to aggregate is 5
zero count is 0
num burn above 0.01 is 35

In [315]:
def get_temporal_category(date_string, num_days):
    num = pd.to_datetime(date_string).dayofyear
    temporal_group = (num - 1) // num_days + 1
    return temporal_group

In [316]:
pd.set_option('display.min_rows',300)
pd.set_option('display.max_rows',300)
longitude_max = df['Longitude'].max()
longitude_min = df['Longitude'].min()
latitude_max = df['Latitude'].max()
latitude_min = df['Latitude'].min()

my_filter = (total_burn_data['LATITUDE'] <= latitude_max) & (total_burn_data['LATITUDE'] >= latitude_min)
my_filter2 = (total_burn_data['LONGITUDE'] <= longitude_max) & (total_burn_data['LONGITUDE'] >= longitude_min)
kelowna_burn_data = total_burn_data[my_filter & my_filter2]
kelowna_burn_data[:300]

     IGNITION_DATE  FIRE_SIZE_HA   LATITUDE   LONGITUDE
2       2017/02/10         0.009  50.889400 -119.320100
9       2017/04/03         0.009  50.172900 -119.362000
46      2017/04/21         0.009  49.816600 -119.758600
77      2017/05/02         0.000  49.949400 -119.558300
86      2017/05/05         0.009  49.506200 -119.514800
136     2017/05/22         0.009  50.956600 -120.122500
144     2017/05/23         1.000  50.218300 -119.194800
145     2017/05/23         4.700  50.292600 -118.983000
151     2017/05/23         0.009  50.011500 -119.398600
166     2017/05/25         0.009  50.230500 -119.514400
189     2017/05/28         0.000  50.719600 -120.140200
218     2017/05/30         0.000  50.811200 -120.229500
245     2017/06/02         0.009  50.598000 -120.036000
247     2017/06/03         0.009  50.083500 -119.792100
260     2017/06/04         0.009  49.801500 -119.837900
265     2017/06/05         0.009  50.868000 -120.233900
272     2017/06/05         0.000  49.955700 -119.527800
273     2017/06/06         0.100  50.430000 -119.619400
274     2017/06/06         0.009  50.662800 -119.059200
278     2017/06/06         0.009  50.871500 -119.270800
307     2017/06/08         0.009  50.686100 -119.366200
310     2017/06/09         0.009  50.434700 -119.360900
312     2017/06/09         0.009  50.849100 -119.413300
319     2017/06/12         0.009  50.208900 -119.173700
322     2017/06/13         2.000  49.947800 -119.500500
325     2017/06/14         0.009  49.904400 -119.702200
333     2017/06/16         0.020  50.907200 -118.200800
342     2017/06/19         0.000  50.635000 -120.298600
349     2017/06/20         0.009  49.996300 -119.316700
352     2017/06/20         1.100  50.936500 -119.102200
353     2017/06/20         0.800  50.914100 -120.237900
359     2017/06/22         0.009  50.190100 -119.332900
375     2017/06/23         0.009  49.683500 -119.724700
378     2017/06/24         0.530  49.716100 -119.802600
383     2017/06/24         0.009  50.663500 -120.101700
387     2017/06/25         0.009  50.270000 -118.609700
389     2017/06/25         0.009  49.993600 -119.331500
395     2017/06/25         0.009  50.294600 -120.309600
405     2017/06/25         0.009  50.272500 -118.606900
409     2017/06/25         0.009  50.059200 -119.222400
415     2017/06/26         0.009  49.506200 -119.644300
429     2017/06/26         0.800  49.662400 -118.793200
441     2017/06/26         0.000  50.800800 -119.761600
448     2017/06/27         0.009  49.876100 -119.704700
457     2017/06/27         0.000  49.714800 -118.904600
462     2017/06/28         0.000  50.648300 -119.963400
473     2017/06/29         0.009  49.777200 -119.455200
477     2017/06/30         0.009  50.057300 -119.234900
482     2017/06/30         0.009  50.081800 -119.083900
502     2017/07/01         0.009  49.903800 -119.241300
504     2017/07/01         0.009  49.898300 -119.057100
519     2017/07/01         0.009  50.136300 -119.011900
527     2017/07/01         0.009  50.088400 -119.447300
547     2017/07/02         0.009  50.143800 -119.382000
557     2017/07/02         0.009  49.953000 -119.249500
558     2017/07/02         0.009  50.590200 -119.634000
565     2017/07/02         0.009  50.286900 -119.644100
569     2017/07/03         0.009  50.132800 -119.235300
573     2017/07/03         0.009  50.984400 -119.094800
577     2017/07/03         0.009  50.759000 -118.553000
579     2017/07/03         0.009  50.134600 -118.996200
580     2017/07/03         0.009  50.559100 -118.717600
583     2017/07/03         0.009  50.085600 -119.195300
586     2017/07/03         0.009  49.648100 -119.927300
590     2017/07/03         0.009  50.057400 -119.235200
594     2017/07/03         0.009  50.012600 -119.091700
600     2017/07/03         0.009  50.803100 -119.694800
601     2017/07/03         0.009  49.609500 -119.084000
611     2017/07/04         0.009  49.835300 -119.388500
693     2017/07/07         0.009  50.430500 -119.680400
823     2017/07/07         0.009  50.447200 -119.661500
856     2017/07/07         0.600  50.421200 -119.681300
935     2017/07/08         0.009  49.569900 -120.137900
936     2017/07/08         0.000  50.280700 -120.303900
937     2017/07/08         0.800  49.565200 -120.142600
946     2017/07/08         0.009  50.795200 -120.152600
966     2017/07/08         0.009  50.142000 -119.269500
967     2017/07/08         0.400  50.111200 -119.315900
989     2017/07/09         0.000  50.945600 -120.308400
998     2017/07/09         0.100  50.874100 -120.218800
1000    2017/07/09         0.009  50.670200 -119.248300
1045    2017/07/10         0.002  49.773900 -118.304000
1053    2017/07/10         0.003  49.511900 -118.212500
1080    2017/07/10         0.060  49.764900 -118.211300
1089    2017/07/11         0.000  50.185900 -119.336300
1090    2017/07/11         0.009  49.719100 -119.761400
1091    2017/07/11         0.009  50.033200 -119.345100
1096    2017/07/11         0.000  50.632900 -120.156400
1109    2017/07/12         0.009  50.939000 -118.814300
1119    2017/07/12         0.000  50.247900 -118.625500
1121    2017/07/13         0.009  49.569900 -120.137900
1131    2017/07/14         0.009  50.012000 -119.092200
1143    2017/07/15         0.009  50.017100 -119.104700
1146    2017/07/15        55.000  50.034500 -119.445300
1148    2017/07/15         0.009  49.770200 -119.969500
1150    2017/07/15         0.009  49.830300 -119.086500
1165    2017/07/16         0.000  50.373800 -119.064500
1184    2017/07/16         0.009  49.875900 -119.705200
1205    2017/07/17      1790.000  49.713450 -119.764633
1214    2017/07/18         0.009  50.207100 -119.505500
1224    2017/07/19         0.009  50.611700 -120.224100
1228    2017/07/19         0.900  50.657500 -118.797300
1232    2017/07/19         1.000  50.139800 -119.790100
1234    2017/07/19         0.009  50.843200 -118.497100
1235    2017/07/19         1.500  50.851400 -118.499500
1237    2017/07/19         0.000  50.113300 -119.713300
1240    2017/07/19         0.010  50.510700 -119.708400
1242    2017/07/19         0.009  50.596900 -119.695000
1247    2017/07/19         0.100  50.499700 -119.689200
1248    2017/07/19         0.000  50.776400 -119.148200
1251    2017/07/19         0.009  50.969900 -119.079300
1254    2017/07/19         0.800  50.753200 -119.596300
1274    2017/07/20         0.009  50.951400 -118.273700
1275    2017/07/20         0.009  50.942900 -119.112500
1279    2017/07/20         8.000  50.987200 -119.129100
1282    2017/07/20         0.190  50.114100 -119.824900
1285    2017/07/20         0.009  50.960000 -119.699700
1291    2017/07/20         0.009  50.579700 -120.206100
1292    2017/07/20         0.009  50.602900 -118.845800
1295    2017/07/20         0.000  50.827000 -119.395800
1300    2017/07/20         0.068  50.010400 -118.240700
1301    2017/07/20         0.000  50.751100 -120.144800
1304    2017/07/20         1.770  50.876300 -120.001300
1318    2017/07/20         0.500  49.507800 -119.634200
1333    2017/07/21         0.009  49.824100 -119.775100
1344    2017/07/22         0.009  50.868600 -119.083000
1350    2017/07/22         0.009  50.751500 -119.757500
1352    2017/07/22         0.009  49.742100 -119.772800
1368    2017/07/23         0.009  50.388200 -118.773800
1369    2017/07/23         0.009  50.033000 -119.290200
1374    2017/07/23         0.000  49.777400 -119.826700
1376    2017/07/23         0.009  50.723600 -119.032500
1381    2017/07/23         0.000  50.923000 -119.551800
1388    2017/07/24         0.009  50.688100 -119.136300
1391    2017/07/24         0.300  49.581600 -119.773600
1408    2017/07/26       150.000  50.532500 -119.838100
1415    2017/07/26         0.000  50.185300 -118.617500
1428    2017/07/27         0.000  49.607000 -118.911300
1434    2017/07/27         0.000  50.642600 -119.209000
1436    2017/07/27         0.000  50.884400 -119.672200
1448    2017/07/28         0.009  50.878200 -118.830700
1453    2017/07/28         0.000  50.369500 -118.815900
1457    2017/07/29         0.100  50.680900 -120.264300
1459    2017/07/29         0.000  50.099800 -119.254300
1464    2017/07/29         0.000  50.122300 -119.508200
1474    2017/07/29         0.000  50.482800 -119.828100
1477    2017/07/29         0.000  49.612500 -119.435800
1478    2017/07/29         0.200  49.556700 -119.566500
1483    2017/07/29         0.009  49.504300 -119.616800
1488    2017/07/30         0.000  50.647500 -119.934900
1493    2017/07/30         0.000  49.596600 -120.204200
1501    2017/07/30         0.700  49.906300 -119.481900
1505    2017/07/31         0.009  50.500100 -119.832000
1506    2017/07/31         3.900  50.499300 -119.831700
1515    2017/07/31         0.009  50.488600 -119.832200
1517    2017/07/31         0.009  50.486900 -119.830000
1518    2017/07/31         0.009  50.501500 -119.833200
1519    2017/07/31         0.009  50.490600 -119.833200
1520    2017/07/31         0.009  50.491500 -119.833200
1557    2017/08/03         0.009  49.768100 -119.661500
1566    2017/08/04         2.500  49.753900 -119.812800
1568    2017/08/04         0.009  50.054100 -119.237600
1586    2017/08/05         0.000  50.865400 -120.247400
1589    2017/08/05         0.009  50.884600 -119.310800
1614    2017/08/07      2500.000  49.542000 -118.522400
1616    2017/08/07         0.000  50.136400 -119.382400
1620    2017/08/07         0.200  49.571400 -118.467800
1625    2017/08/07         0.009  49.587900 -118.383800
1673    2017/08/10         4.700  50.374100 -119.230100
1732    2017/08/12         0.700  50.034300 -119.403500
1750    2017/08/13         0.000  50.788300 -118.990200
1773    2017/08/14         0.100  50.735500 -120.145600
1779    2017/08/14         0.009  50.967300 -119.820800
1780    2017/08/15         0.400  49.597000 -119.552000
1788    2017/08/16         0.009  49.847400 -119.644500
1789    2017/08/16         0.009  50.253800 -119.207600
1792    2017/08/16         0.000  50.739500 -120.197000
1798    2017/08/17         0.009  50.324200 -118.698200
1799    2017/08/17         0.009  49.835100 -119.646200
1806    2017/08/18         0.200  49.589000 -119.592100
1810    2017/08/18         0.210  49.826700 -119.780900
1823    2017/08/19         0.009  50.907600 -119.086300
1829    2017/08/20         0.009  50.672200 -119.843400
1833    2017/08/20         0.009  49.952800 -119.250600
1838    2017/08/21         0.000  50.131400 -119.358600
1843    2017/08/21         0.100  50.566700 -118.967400
1845    2017/08/22         0.100  50.116200 -119.275600
1846    2017/08/22         0.000  50.607700 -119.084400
1848    2017/08/22         2.100  49.866800 -119.336000
1852    2017/08/23         0.450  50.671200 -118.839800
1855    2017/08/23         0.000  50.920600 -119.291300
1859    2017/08/23         0.100  50.872700 -118.633700
1861    2017/08/23         1.100  50.785900 -118.515600
1866    2017/08/23         0.100  50.795700 -118.494900
1872    2017/08/23         0.100  50.616600 -119.021200
1877    2017/08/24       465.000  49.864100 -119.193300
1882    2017/08/24         0.060  50.898200 -118.965600
1884    2017/08/24         0.000  50.924900 -118.689000
1886    2017/08/24         0.009  50.927800 -118.468500
1887    2017/08/24         0.000  50.647200 -119.298700
1898    2017/08/24         0.009  50.380400 -118.741800
1902    2017/08/24         0.009  50.850000 -119.597400
1906    2017/08/25         0.009  50.607600 -118.847800
1907    2017/08/25         0.009  50.918000 -118.725600
1908    2017/08/25         0.000  50.917800 -118.724700
1909    2017/08/25         0.009  50.390500 -119.316900
1915    2017/08/26         0.100  50.630700 -120.034600
1918    2017/08/26         0.000  50.376000 -119.353800
1919    2017/08/27         0.009  50.339100 -118.787300
1949    2017/08/29         0.200  50.304900 -119.190600
1952    2017/08/29         0.009  50.096100 -119.178400
1961    2017/08/30         0.009  49.593000 -119.732400
1980    2017/08/30         0.009  50.682600 -120.269900
1987    2017/08/30         0.009  50.077000 -119.411400
2014    2017/09/01         0.200  49.598500 -119.736300
2018    2017/09/02         0.009  50.094300 -119.180300
2019    2017/09/02         0.000  50.884000 -119.300700
2021    2017/09/02         0.500  50.967400 -120.030000
2022    2017/09/02      2224.000  49.729800 -119.829000
2041    2017/09/03        35.000  49.667800 -119.281500
2044    2017/09/03         0.900  50.756900 -119.323700
2057    2017/09/05         0.009  50.860600 -118.995900
2061    2017/09/06         0.009  50.438000 -119.505700
2075    2017/09/08         0.009  50.849600 -120.022500
2082    2017/09/08         0.100  50.939600 -118.494700
2083    2017/09/08         0.009  50.953700 -118.595800
2088    2017/09/08         0.000  50.855700 -118.816600
2092    2017/09/09         0.100  50.688700 -120.025000
2095    2017/09/09         0.800  50.854200 -118.431500
2101    2017/09/09         0.009  49.512500 -119.695800
2109    2017/09/11         0.000  50.555300 -120.230800
2113    2017/09/11         0.009  49.571900 -119.572200
2126    2017/09/14         0.009  49.828900 -119.649400
2129    2017/09/14         0.009  50.779800 -119.713800
2147    2017/09/18         0.100  49.867000 -119.693500
2151    2017/09/18         0.009  49.830200 -119.672200
2155    2017/09/19         0.000  50.176300 -119.404600
2158    2017/09/20         0.090  49.735300 -118.236000
2184    2017/09/26         0.000  50.860700 -118.837600
2187    2017/09/27         0.009  50.911500 -119.287800
2188    2017/09/27         0.000  50.650200 -119.949800
2195    2017/09/27         0.009  50.211100 -118.868300
2198    2017/09/29         0.009  50.937400 -118.193700
2204    2017/10/02         6.000  49.757700 -119.695300
2205    2017/10/02         0.009  50.551700 -119.378900
2210    2017/10/03         0.009  50.232200 -119.015000
2217    2017/10/03         0.009  50.452500 -119.803000
2227    2017/10/06         0.009  49.770800 -119.223500
2228    2017/10/06         0.100  50.286300 -119.939200
2229    2017/10/07         0.009  49.757000 -119.907600
2231    2017/10/07         0.009  50.624600 -119.926000
2244    2017/10/15         0.009  49.813700 -119.749900
2254    2017/10/19         0.009  50.577800 -118.948700
2257    2017/10/20         0.009  50.259000 -119.178300
2272    2017/10/25         0.250  49.756100 -118.625000
2274    2017/10/25         0.250  49.756134 -118.625000
2282    2017/10/29         0.009  49.805500 -119.674400
2328    2018/03/30         0.009  50.779700 -120.198200
2331    2018/03/31         0.009  50.645000 -119.976000
2335    2018/04/03         0.250  50.645050 -120.049767
2336    2018/04/03         0.250  50.645100 -120.049800
2337    2018/04/04       141.000  50.769017 -119.758267
2338    2018/04/04       141.000  50.769000 -119.758300
2341    2018/04/11         3.000  49.501600 -119.625400
2342    2018/04/11         3.000  49.501617 -119.625366
2393    2018/04/25         0.009  49.834100 -119.350000
2410    2018/04/26         8.000  50.768900 -119.727000
2414    2018/04/26         8.000  50.768917 -119.726967
2450    2018/04/30         2.200  50.700950 -119.129133
2517    2018/05/06         2.200  50.701000 -119.129100
2528    2018/05/06         0.009  50.637600 -120.221500
2569    2018/05/10         0.009  50.427100 -119.164800
2627    2018/05/14         0.900  50.610700 -120.193000
2639    2018/05/14         0.900  50.610700 -120.193000
2672    2018/05/17         0.009  50.650400 -120.148800
2690    2018/05/18         0.400  50.665200 -120.048500
2700    2018/05/18         0.400  50.665183 -120.048483
2706    2018/05/19         0.009  50.057000 -119.234800
2711    2018/05/19         0.009  50.621417 -119.666000
2725    2018/05/19         0.009  50.621400 -119.666000
2743    2018/05/20         0.009  50.254900 -118.746000
2754    2018/05/20         0.009  50.796600 -119.653200
2769    2018/05/20         0.009  50.205300 -119.179900
2776    2018/05/20         0.009  50.267900 -119.160200
2784    2018/05/20         0.009  50.205318 -119.179886
2794    2018/05/20         0.009  50.374500 -118.525600
2804    2018/05/21         0.009  50.289500 -118.885500
2827    2018/05/21         0.009  50.250000 -119.251600
2832    2018/05/22         0.100  49.992001 -119.340683
2837    2018/05/22         0.100  49.992000 -119.340700
2860    2018/05/23         0.009  50.104600 -119.324600
2877    2018/05/25         0.009  50.793266 -119.635468
2878    2018/05/25         0.009  50.761300 -119.515600
2879    2018/05/25         0.009  50.793300 -119.635500
2888    2018/05/25         0.009  50.761284 -119.515602
2913    2018/05/26         0.009  50.778800 -119.231500
2915    2018/05/26         3.500  49.832100 -119.590400
2922    2018/05/26         3.500  49.832100 -119.590383
2925    2018/05/27         0.100  49.715200 -120.217200
2932    2018/05/27         0.009  49.777000 -119.455600

In [318]:
import os

def spatially_split_burn(all_burn, num_long_splits, num_lat_splits, year_min, year_max, temporal_min, temporal_max, window):
    base_dir = './data/final-burn'
    
    longitude_max = all_burn['LONGITUDE'].max()
    longitude_min = all_burn['LONGITUDE'].min()
    latitude_max = all_burn['LATITUDE'].max()
    latitude_min = all_burn['LATITUDE'].min()
    longitude_distance = longitude_max - longitude_min
    latitude_distance = latitude_max - latitude_min

    long_split_distance = longitude_distance / num_long_splits
    lat_split_distance = latitude_distance / num_lat_splits

    long_track = longitude_min
    lat_track = latitude_min

    for year in range(year_min,year_max):        
        for temporal_split in range(temporal_min,temporal_max):
            segmented_burn = []
            
            burn_filter_year = all_burn['IGNITION_DATE'].str[:4] == str(year)
            burn_filter_temporal = all_burn['IGNITION_DATE'].apply(get_temporal_category, args=(window,)) == temporal_split
            
            for i in range(num_lat_splits):
                lat_track = latitude_min + i * lat_split_distance
                
                for j in range(num_long_splits):
                    long_track = longitude_min + j * long_split_distance

                    latitude_mask_burn = (all_burn['LATITUDE'] < lat_track + lat_split_distance) & (all_burn['LATITUDE'] >= lat_track)
                    longitude_mask_burn = (all_burn['LONGITUDE'] < long_track + long_split_distance) & (all_burn['LONGITUDE'] >= long_track)

                    burn_filter_final = burn_filter_year & burn_filter_temporal & latitude_mask_burn & longitude_mask_burn
                    
                    numerical_size = all_burn[burn_filter_final]['FIRE_SIZE_HA'].sum(axis=0)
                    
                    segmented_burn.append(numerical_size)
            
            curr_dir = base_dir + f'/{year}'
            if not os.path.exists(curr_dir):
                os.makedirs(curr_dir)
            
            df = pd.DataFrame(segmented_burn)
            df.to_csv(curr_dir + f'/group_{temporal_split}.csv', index = False, header = False)

In [319]:
spatially_split_burn(kelowna_burn_data, 6, 6, 2017, 2024, 1, 53, 7)

In [324]:
check_set = set()

def temporal_process(year_min, year_max, termporal_min, temporal_max, fine_split_min, fine_split_max, window):
    weather_dir = './data/final-weather/'
    base_dir = "./data/weather-stations/kelowna/"
    
    for curr_year in range(year_min,year_max):

        for i in range(fine_split_min,fine_split_max):
            filtered_df = pd.read_csv(base_dir + f"fine_area_{i}_stations.csv")        

            for temporal_split in range(termporal_min,temporal_max):
                temporal_dataframes = []

                for index, row in filtered_df.iterrows():
                    network_name = row['Network Name']
                    native_id = row['Native ID']

                    file_path = f'./data/weather/{curr_year}/{network_name}/{native_id}.csv'
                    temp_df, temporal_data = [], []

                    if os.path.exists(file_path):
                        temp_df = pd.read_csv(file_path, skiprows = 1)
                    else:
                        check_set.add((network_name, native_id))
                        continue

                    if len(temp_df) != 0:
                        temporal_data = temp_df[temp_df[' time'].apply(get_temporal_category, args=(window,)) == temporal_split]
                    
                    if len(temporal_data) != 0:
                        temporal_dataframes.append(temporal_data)
                
#                 print(temporal_dataframes)
                
                if temporal_dataframes:
                    combined_df = pd.concat(temporal_dataframes, ignore_index=True, axis=0, join='outer')
                    combined_df.fillna(-999, inplace = True)
                    if not os.path.exists(weather_dir + f'{curr_year}/group_{temporal_split}'):
                        os.makedirs(weather_dir + f'{curr_year}/group_{temporal_split}')
                    combined_df.to_csv(weather_dir + f'{curr_year}/group_{temporal_split}/fine_area_{i}_weather.csv', index=False, header=True)

In [ ]:
temporal_process(2017, 2022, 1, 53, 1, 37, 7)

In [309]:
print(len(check_set))

395

Training Pipeline Begins

In [251]:
import numpy as np

def align_data():
    curr_year = 2017
    weather_process_base_dir = './data/final-weather/2017'
    new_dir = './data/train-weather/2017'
    
    for group in range(1,13):
        single_dfs = []
        fine_area_weather_missing = set()
        for i in range(1,101):
            file_path = weather_process_base_dir + f'/group_{group}/fine_area_{i}_weather.csv'
            df = []
            if os.path.exists(file_path):
                df = pd.read_csv(file_path)
            else:
                fine_area_weather_missing.add(i)
                continue
            df.replace('None', np.nan, inplace=True)
            
            df = df.apply(pd.to_numeric, errors='coerce')

#             threshold = len(df) * 0.5
            df.replace(-999, np.nan, inplace=True) 

#             cols_to_drop = df.columns[df.isnan().sum() > threshold]
#             df.drop(cols_to_drop, axis=1, inplace=True)

            # impute remaining missing values with column mean
#             df.fillna(df.mean(), inplace=True)

            aggregations = {}
            
            for col in df.columns:
                if pd.api.types.is_numeric_dtype(df[col]):
                    aggregations[col] = 'mean'  
                else:
                    df.drop(col)
            
            df = df.agg(aggregations)
            df = df.to_frame().transpose()
            
            single_dfs.append(df)
        
        if os.path.exists(f'./data/final-burn/{curr_year}/group_{group+1}.csv') and single_dfs:
            combined_df = pd.concat(single_dfs, ignore_index= True)
            threshold = len(combined_df) * 0.8
            cols_to_drop = combined_df.columns[combined_df.isna().sum() > threshold]
#             print(cols_to_drop)
            combined_df.drop(cols_to_drop, axis=1, inplace=True)
            combined_df.fillna(combined_df.mean(), inplace=True)
            combined_df.to_csv(new_dir + f'/group_{group}.csv', index = False)
            
            burn_area_df = pd.read_csv(f'./data/final-burn/{curr_year}/group_{group+1}.csv', header = None, names=['burn_area'])
            for index, row in burn_area_df.iterrows():
                if index+1 in fine_area_weather_missing:
                    burn_area_df.drop(index, inplace = True)
            burn_area_df.to_csv(f'./data/train-burn/{curr_year}/group_{group}.csv', index = False)

In [252]:
pd.set_option('display.min_rows',70)
pd.set_option('display.max_rows',70)
align_data()

/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/jk/lb9w5x9s3dvcp6jxj99nx1vh0000gn/T/ipykernel_90489/859124636.py:15: DtypeWarning: Columns (1,2,4,6,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [107]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-2.0.3-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 8.8 MB/s eta 0:00:00:00:0100:01
Requirement already satisfied: numpy in /Users/aryans0921/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /Users/aryans0921/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)
WARNING: Error parsing requirements for jedi: [Errno 2] No such file or directory: '/Users/aryans0921/opt/anaconda3/lib/python3.9/site-packages/jedi-0.18.1.dist-info/METADATA'
Installing collected packages: xgboost
Successfully installed xgboost-2.0.3

In [109]:
import pandas as pd
import xgboost as xgb
from sklearn.metrics import mean_squared_error

for group in range(15,40):
    

train_df = pd.read_csv('./data/train-weather/2017/group_25.csv')
target_df = pd.read_csv('./data/train-burn/2017/group_25.csv')

X_train = train_df.iloc[:45, :]
y_train = target_df.iloc[:45, 0]
X_test = train_df.iloc[45:60, :]
y_test = target_df.iloc[45:60, 0]

model = xgb.XGBRegressor(objective='reg:squarederror')

model.fit(X_train, y_train)

predictions = model.predict(X_test)

for i in range(len(predictions)):
    print(f"Predicted: {predictions[i]}, Actual: {y_test.iloc[i]}")

mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error on Test Data:", mse)

Predicted: 0.8843307495117188, Actual: 0.0
Predicted: 1.675981879234314, Actual: 0.0
Predicted: -0.00029467607964761555, Actual: 0.0
Predicted: 1.675981879234314, Actual: 0.0
Predicted: 1.675981879234314, Actual: 0.0
Predicted: -0.04096442833542824, Actual: 0.0
Predicted: 3.3134653568267822, Actual: 0.0
Predicted: 0.6431534886360168, Actual: 0.0
Predicted: 0.0005261584301479161, Actual: 0.0
Predicted: 0.6079038977622986, Actual: 0.0
Predicted: 0.3213668167591095, Actual: 0.0
Predicted: 1.675981879234314, Actual: 0.0
Predicted: 0.4828042685985565, Actual: 0.0
Predicted: 0.6353285312652588, Actual: 0.0
Predicted: 1.675981879234314, Actual: 0.0
Mean Squared Error on Test Data: 1.8220373856858303

In [ ]:
# import os
# my_filter = ['ONE_DAY_PRECIPITATION', 'ONE_DAY_RAIN', 'MIN_TEMP', 'ONE_DAY_SNOW', 'time', 'MAX_TEMP']
filtered_df = df
for curr_year in range(2012, 2013):
    yearly_dataframes = []

    for index, row in filtered_df.iterrows():
        network_name = row['Network Name']
        native_id = row['Native ID']
        
        file_path = f'./data/weather/{curr_year}/{network_name}/{native_id}.csv'

        if os.path.exists(file_path):
            temp_df = pd.read_csv(file_path, skiprows=1)
            
            yearly_dataframes.append(temp_df)

    if yearly_dataframes:
        combined_df = pd.concat(yearly_dataframes, ignore_index=True)
        combined_df.columns = [i.lstrip() for i in combined_df.columns]
#         existing_columns = [c for c in my_filter if c in combined_df.columns]
#         combined_df = combined_df[existing_columns]
#       print(combined_df.columns)
        combined_csv_path = f'./training_data_20123/combined_data_{curr_year}.csv'
        combined_df.to_csv(combined_csv_path, index=False)
        print(combined_df)